<img src="https://www.freecodecamp.org/news/content/images/2020/07/numpy.png" alt="numpy">

# 🚀 Unleashing the Power of NumPy: Your Gateway to Scientific Computing 🧠

## 🌟 Introduction: Revolutionize Your Python with NumPy! 🌟

Welcome to the exhilarating world of **NumPy** - the beating heart of scientific computing in Python! 🐍💻

**NumPy**, short for **Numerical Python**, isn't just a library; it's a game-changer that transforms Python into a powerhouse of numerical computation. Imagine having a turbocharged engine for your code, capable of crunching numbers at lightning speed - that's NumPy for you!

### 🔬 Why NumPy? Because Science Demands Power!

In the realm of data science, machine learning, and scientific research, NumPy stands as the cornerstone upon which giants are built. It's the secret sauce that makes Python a preferred language for scientists, engineers, and data wizards worldwide.

### 🚀 Prepare for Liftoff: Your NumPy Journey Begins Here!

This crash course is your launchpad into the NumPy universe. Buckle up as we explore the galaxies of multidimensional arrays, navigate the asteroid fields of advanced indexing, and warp through the space-time continuum of broadcasting!

---

## 📚 Your Expedition Itinerary: What Awaits You

1. **🎭 The Grand Entrance: Importing NumPy**
   - Master the art of summoning NumPy's power into your Python realm.

2. **🏗️ Array Alchemy: Crafting Multidimensional Wonders**
   - Forge 1D, 2D, and mind-bending multidimensional arrays with ease.

3. **🔍 Element Whisperer: Accessing and Altering Array Elements**
   - Become one with your data - reach in and manipulate it at will.

4. **💾 Data Persistence: Saving and Loading Your Creations**
   - Learn the secrets of preserving your array masterpieces for posterity.

5. **✂️ Slice and Dice: Surgical Precision with Array Subsets**
   - Wield the scalpel of slicing to dissect arrays with pinpoint accuracy.

6. **👥 Doppelgänger Dilemma: Views vs. Copies**
   - Unravel the mysteries of array duplication and reference.

7. **🎭 Boolean Sorcery: Mastering Logical Indexing**
   - Harness the power of truth to filter and transform your data.

8. **🔄 Sorting Chaos: Bringing Order to Your Arrays**
   - Learn to command your data into perfect formation.

9. **⚡ Elemental Fury: Unleashing Operations Across Arrays**
   - Perform mathematical miracles on entire datasets in the blink of an eye.

10. **🔮 The Art of Broadcasting: Bending Dimensions to Your Will**
    - Discover the magic that allows operations between arrays of different sizes.

---

### 🌠 Embark on Your NumPy Odyssey!

Prepare to transcend the ordinary and enter a realm where data bends to your will. By the end of this journey, you'll wield NumPy with the finesse of a digital virtuoso, ready to tackle the most daunting computational challenges.

Remember, in the world of NumPy, you're not just coding - you're conducting a symphony of numbers, painting with data, and sculpting the very fabric of scientific computing.

Are you ready to revolutionize your Python experience? Let's dive in and unlock the infinite possibilities that await! 🚀🔓✨

# 💡 **Why Use NumPy?**

You may be wondering, why use **NumPy** when Python already has lists, which were covered in the **Intro to Python** lessons? 🤔

While Python lists are quite versatile, **NumPy** brings **several key advantages** that make it superior for many scientific and data-intensive tasks.

---

## 🚀 **Key Features of NumPy** 

### ⚡ **Speed**
One of the most important reasons to use NumPy is **speed**. When working with **large arrays**, NumPy can be **several orders of magnitude faster** than Python lists. This speed boost comes from:

- **Memory efficiency**: NumPy arrays are stored more compactly in memory.
- **Optimized algorithms**: NumPy uses highly efficient algorithms for operations like arithmetic, statistics, and linear algebra.

### 🔢 **Multidimensional Array Structures**
Another powerful feature of NumPy is its ability to handle **multidimensional arrays**, like **vectors** and **matrices**.

- You'll explore **vectors and matrices** in the Linear Algebra section later in this course.
- Many **machine learning algorithms** rely heavily on matrix operations. For example, during **Neural Network** training, you'll often need to perform many matrix multiplications.
  
NumPy is designed to perform these **Linear Algebra operations efficiently**, making it an ideal tool for **machine learning** and **AI** applications.

### 🔍 **Optimized Mathematical Functions**
NumPy comes with a wealth of **built-in mathematical functions** that are optimized for performance. These functions allow you to:

- Perform **complex mathematical computations** quickly.
- Write more **concise and readable code**, avoiding lengthy and complex loops.
  
By leveraging these optimized functions, your programs will not only run faster but also be **cleaner** and **easier to understand**.

---

## 🌟 **Why NumPy is Essential**

NumPy's popularity extends far beyond its direct use. Many other Python packages, such as **Pandas**, are built on top of NumPy. This makes NumPy a **foundational package** for anyone working in **data science**, **machine learning**, or **scientific computing**.

It's clear that **NumPy** is more than just a replacement for Python lists—it's a **must-have** tool for efficient, high-performance computing. 🔥

---


# 🧠 **The Core of NumPy: The `ndarray`**

At the heart of **NumPy** is the **ndarray**, where **nd** stands for **n-dimensional**. An `ndarray` is a **multidimensional array** consisting of elements that are **all of the same type**.

---

## 🟦 **What is an `ndarray`?**

- An `ndarray` is essentially a **grid** that can take on **many shapes** and can hold a variety of data types, such as numbers or strings.
- One common application in **Machine Learning** involves using an `ndarray` to store the **pixel values** of an image that will be fed into a **Neural Network** for tasks like **image classification**.

In many Machine Learning problems, you'll encounter `ndarrays` in different forms, so understanding how they work is key to efficient data manipulation.

---

## 🔄 **How to Import NumPy**

Before we can start working with `ndarrays`, we need to first **import** NumPy into Python. It is common practice to import NumPy using the alias **`np`** for convenience. This can be done by executing the following command:





In [1]:
import numpy as np

### Simply type this command in your **Jupyter Notebook** or Python environment to begin working with **NumPy**!

---

Once you've imported NumPy, you'll be ready to dive into creating and manipulating `ndarrays` to solve complex computational problems. Let's get started! 🚀 


# 📐 **Creating `ndarrays` in NumPy**

There are several ways to create **`ndarrays`** in NumPy. In the following lessons, we will explore two ways to create `ndarrays`:

1. **Using regular Python lists**
2. **Using built-in NumPy functions**

---

## 🔧 **Creating `ndarrays` Using Python Lists**

In this section, we will create `ndarrays` by providing **Python lists** to the NumPy **`np.array()`** function. This can create some confusion for beginners, but it is important to remember that:

- **`np.array()`** is **NOT a class**; it’s just a **function** that returns an `ndarray`.

For clarity, the examples throughout these lessons will use **small and simple `ndarrays`**. Let's start by creating **1-Dimensional (1D) `ndarrays`**.


In [2]:
# We import NumPy into Python
import numpy as np

# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# Let's print the ndarray we just created using the print() command
print('x = ', x)

x =  [1 2 3 4 5]


# 🔎 **Understanding Array Terminology**

Before we dive deeper, let's pause and introduce some **useful terminology** when working with **NumPy arrays**:

### 🟦 **Rank of Arrays**
- A **1D array** is referred to as a **rank 1 array**.
- In general, an **N-Dimensional array** has **rank N**.
  - For example, a **2D array** is referred to as a **rank 2 array**.

---

### 🔢 **Shape of Arrays**
- The **shape** of an array describes its **size along each dimension**.
  - For instance, the **shape** of a rank 2 array corresponds to the number of **rows and columns** in the array.
- **NumPy `ndarrays`** come with attributes that allow you to obtain such information **intuitively**.
  - The **`.shape` attribute** returns a **tuple** of N positive integers, each specifying the size along a specific dimension.

---

## 🟢 **Example: Getting the Shape, Type, and Data-Type (`dtype`) of an `ndarray`**

In the example below, we will:

1. Create a **rank 1 array**.
2. Learn how to obtain its **shape**.
3. Discover its **type**.
4. Find out the **data-type (`dtype`)** of its elements.



In [3]:
# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('x = ', x)
print()

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


# 🔍 **Interpreting the `ndarray` Attributes**

In our previous example, we observed the following:

1. The **`.shape`** attribute returned the tuple **`(5,)`**, indicating that:
   - **`x`** is a **rank 1** array (i.e., it has only **one dimension**).
   - It contains **5 elements**.

2. The **`type()`** function confirmed that **`x`** is indeed a **NumPy `ndarray`**.

3. The **`.dtype`** attribute revealed that the elements of **`x`** are stored as **signed 64-bit integers** in memory.

---

### 💡 **NumPy's Support for Multiple Data Types**
One of the key advantages of NumPy over Python lists is its ability to handle a **variety of data types**. NumPy supports far more data types than standard Python lists. You can explore all the supported data types by visiting the link below:

🔗 [NumPy Data Types](https://numpy.org/doc/stable/user/basics.types.html)

---

### 🟢 **Example: Creating a Rank 1 `ndarray` of Strings**

As mentioned earlier, **`ndarrays`** can also hold **strings**. Let's create a **rank 1 `ndarray` of strings** by passing a **Python list of strings** to the **`np.array()`** function.


In [4]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# We print x
print()
print('x = ', x)
print()

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  ['Hello' 'World']

x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


# 🧵 **Exploring the `ndarray` of Strings**

In the previous example, we observed the following:

1. The **`.shape`** attribute tells us that **`x`** now has **2 elements**.
2. Even though **`x`** holds **strings**, the **`type()`** function still confirms that **`x`** is a **NumPy `ndarray`**.
3. The **`.dtype`** attribute shows that the elements in **`x`** are stored in memory as **Unicode strings of 5 characters**.

---

### ⚠️ **Key Difference: Python Lists vs `ndarrays`**

One crucial difference between **Python lists** and **NumPy `ndarrays`** is that:

- In a **Python list**, you can mix data types (e.g., integers and strings).
- In a **NumPy `ndarray`**, **all elements must be of the same type**.

If you pass a **Python list** containing **both integers and strings** to the **`np.array()`** function, **NumPy** will automatically convert **all elements to strings**. Let's see this in action in the next example:


In [5]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  ['1' '2' 'World']

x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U11


# 🔤 **Handling Mixed Data Types in `ndarrays`**

In the last example, we saw that even though the **Python list** contained **mixed data types** (integers and strings), NumPy automatically converted all the elements to **Unicode strings of 21 characters**.

---

### 🧠 **Key Takeaway:**
While we won't be using `ndarrays` with strings for the rest of this **introduction to NumPy**, it's important to remember that **`ndarrays` can hold strings** when necessary.

---

## 🟢 **Next: Creating a Rank 2 `ndarray`**

Now, let's move forward and see how we can create a **rank 2 `ndarray`** from a **nested Python list**.


In [6]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


# 📊 **Creating a Rank 2 `ndarray`**

In the previous example, we created a rank 2 `ndarray` **`Y`** from a nested Python list. The observations were as follows:

1. The **`.shape`** attribute returned the tuple **`(4, 3)`**, indicating that:
   - **`Y`** is of **rank 2** (i.e., it has **4 rows** and **3 columns**).
   
2. The **`.size`** attribute confirmed that **`Y`** contains a total of **12 elements**.

---

### ⚙️ **Automatic Data Type Assignment**
When NumPy creates an `ndarray`, it automatically assigns its **`dtype`** based on the type of the elements used for its creation. 

- Up to this point, we have only created `ndarrays` with integers and strings. 
- We noticed that when we create an `ndarray` with only **integers**, NumPy assigns the **`dtype`** as **`int64`**.

---

## 🟢 **Next Steps: Mixing Floats and Integers**
Let's explore what happens when we create `ndarrays` that include **both floats and integers**.


In [7]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


# 🔢 **Understanding Data Types in `ndarrays`**

In our previous exploration, we found:

1. When we create an `ndarray` with only **floats**, NumPy stores the elements in memory as **64-bit floating point numbers (`float64`)**.
  
2. However, when we create an `ndarray` containing **both floats and integers** (as seen with the **`z` ndarray**), NumPy assigns the **`float64`** dtype to all elements. This process is known as **upcasting**. 

   - This ensures that all elements are of the same type, with integers being converted to floats to prevent losing precision in numerical computations.

---

### ⚙️ **Specifying Data Types**
While NumPy automatically selects the **`dtype`** of the `ndarray`, it also provides the flexibility to specify a particular **`dtype`** for the elements when creating the `ndarray`. You can do this using the **`dtype`** keyword in the **`np.array()`** function.

---

## 🟢 **Example: Specifying the `dtype`**
Let's see an example of how to specify the **`dtype`** when creating an `ndarray`.


In [8]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print x
print()
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

The elements in x are of type: int64


# 📂 **Specifying Data Types in `ndarrays`**

In the previous example, we observed that:

- Even though we created the `ndarray` with **floats**, by specifying the **`dtype`** as **`int64`**, NumPy converted the floating-point numbers into integers by removing their decimal parts.

### ⚙️ **Why Specify the `dtype`?**
Specifying the **`dtype`** of the `ndarray` can be beneficial in several scenarios:

- **Prevent Accidental Type Selection:** Ensures NumPy does not accidentally choose an unintended data type.
- **Control Precision:** Helps manage the level of precision required for calculations, which can also save memory.

---

## 💾 **Saving `ndarrays` to Files**
Once you have created an `ndarray`, you might want to save it to a file for later use or to share with another program. NumPy provides a straightforward way to save arrays into files. 

### 🔍 **Let’s Explore How to Save `ndarrays`**
Let's see how this is done!


In [9]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)

# 📥 **Saving and Loading `ndarrays`**

The previous example demonstrated how to save the **`x` ndarray** into a file named **`my_array.npy`**.

### 🔄 **Loading Saved `ndarrays`**
You can load the saved `ndarray` back into a variable using the **`load()`** function. Here's how it works:

# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# We print y
print()
print('y = ', y)
print()

# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

In [10]:
# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# We print y
print()
print('y = ', y)
print()

# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)


y =  [1 2 3 4 5]

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


# 🛠️ **Using Built-in Functions to Create `ndarrays`**

One of the fantastic features of NumPy is its ability to create `ndarrays` using built-in functions, allowing you to generate specific types of `ndarrays` in just one line of code. Below are some of the most useful built-in functions for creating `ndarrays`, especially in AI programming.

### 🟢 **Creating an `ndarray` Full of Zeros**
To create an `ndarray` with a specified shape filled with zeros, you can use the **`np.zeros()`** function. 

#### Example:
The function **`np.zeros(shape)`** creates an `ndarray` filled with zeros, where **`shape`** defines the desired dimensions. For instance, if you want to create a rank 2 array with **3 rows** and **4 columns**, you can pass the shape as follows:




In [11]:
# We create a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


As we can see, the `np.zeros()` function creates by default an array with `dtype` float64. If desired, the data type can be changed by using the keyword `dtype`.

Similarly, we can create an `ndarray` with a specified shape that is full of ones. We can do this by using the `np.ones()` function. Just like the `np.zeros()` function, the `np.ones()` function takes as an argument the shape of the `ndarray` you want to make. Let's see an example:


In [12]:
# We create a 3 x 2 ndarray full of ones. 
X = np.ones((3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 


X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


As we can see, the `np.ones()` function also creates, by default, an array with `dtype` **float64**. If desired, the data type can be changed by using the keyword `dtype`.

We can also create an `ndarray` with a specified shape that is full of any number we want. We can do this by using the `np.full()` function. The `np.full(shape, constant value)` function takes two arguments: 

1. **shape**: The shape of the `ndarray` you want to make.
2. **constant value**: The constant value you want to populate the array with.

Let's see an example:


In [13]:
# We create a 2 x 3 ndarray full of fives. 
X = np.full((2,3), 5) 

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)  


X = 
 [[5 5 5]
 [5 5 5]]

X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


The `np.full()` function creates, by default, an array with the same data type as the constant value used to fill in the array. If desired, the data type can be changed by using the keyword `dtype`.

As you will learn later, a fundamental array in Linear Algebra is the **Identity Matrix**. An Identity matrix is a square matrix that has only **1s** in its main diagonal and **0s** everywhere else. The function `np.eye(N)` creates a square \( N \times N \) `ndarray` corresponding to the Identity matrix. Since all Identity Matrices are square, the `np.eye()` function only takes a single integer as an argument. 

Let's see an example:


In [14]:
# We create a 5 x 5 Identity matrix. 
X = np.eye(5)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 


X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


As we can see, the `np.eye()` function also creates, by default, an array with `dtype` **float64**. If desired, the data type can be changed by using the keyword `dtype`. You will learn all about **Identity Matrices** and their use in the Linear Algebra section of this course.

We can also create **diagonal matrices** by using the `np.diag()` function. A diagonal matrix is a square matrix that only has values in its main diagonal. The `np.diag()` function creates an `ndarray` corresponding to a diagonal matrix, as shown in the example below:


In [15]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
X = np.diag([10,20,30,50])

# We print X
print()
print('X = \n', X)
print()


X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]



NumPy also allows you to create `ndarrays` that have evenly spaced values within a given interval. NumPy's `np.arange()` function is very versatile and can be used with either one, two, or three arguments. Below, we will see examples of each case and how they are used to create different kinds of `ndarrays`.

Let's start by using `np.arange()` with only one argument. When used with only one argument, `np.arange(N)` will create a rank 1 `ndarray` with consecutive integers between **0** and **N - 1**. Therefore, notice that if I want an array to have integers between **0** and **9**, I have to use **N = 10**, NOT **N = 9**, as in the example below:


In [18]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [0 1 2 3 4 5 6 7 8 9]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


When used with two arguments, `np.arange(start, stop)` will create a rank 1 `ndarray` with evenly spaced values within the half-open interval \([ \text{start}, \text{stop} )\). This means the evenly spaced numbers will include **start** but exclude **stop**. 

Let's see an example:


In [19]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9. 
x = np.arange(4,10)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [4 5 6 7 8 9]

x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


As we can see, the function `np.arange(4, 10)` generates a sequence of integers with **4** inclusive and **10** exclusive.

Finally, when used with three arguments, `np.arange(start, stop, step)` will create a rank 1 `ndarray` with evenly spaced values within the half-open interval \([ \text{start}, \text{stop} )\), with **step** being the distance between two adjacent values. 

Let's see an example:


In [20]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [ 1  4  7 10 13]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


We can see that **x** has sequential integers between **1** and **13**, but the difference between all adjacent values is **3**.

Even though the `np.arange()` function allows for non-integer steps, such as **0.3**, the output is usually inconsistent due to finite floating-point precision. For this reason, in cases where non-integer steps are required, it is usually better to use the function `np.linspace()`.

The `np.linspace(start, stop, N)` function returns **N** evenly spaced numbers over the closed interval \([ \text{start}, \text{stop} ]\). This means that both the **start** and **stop** values are included. 

We should also note that the `np.linspace()` function needs to be called with at least two arguments in the form `np.linspace(start, stop)`. In this case, the default number of elements in the specified interval will be **N = 50**. 

The reason `np.linspace()` works better than the `np.arange()` function is that `np.linspace()` uses the number of elements we want in a particular interval instead of the step between values. 

Let's see some examples:


In [21]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x = np.linspace(0,25,10)

# We print the ndarray
print()
print('x = \n', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


As we can see from the above example, the function `np.linspace(0, 25, 10)` returns an `ndarray` with **10** evenly spaced numbers in the closed interval \([0, 25]\). We can also see that both the start and end points, **0** and **25** in this case, are included. 

However, you can let the endpoint of the interval be excluded (just like in the `np.arange()` function) by setting the keyword `endpoint=False` in the `np.linspace()` function. 

Let's create the same **x** `ndarray` we created above but now with the endpoint excluded:


In [22]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.
x = np.linspace(0,25,10, endpoint = False)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


As we can see, because we have excluded the endpoint, the spacing between values had to change in order to fit **10** evenly spaced numbers in the given interval.

So far, we have only used the built-in functions `np.arange()` and `np.linspace()` to create rank 1 `ndarrays`. However, we can use these functions to create rank 2 `ndarrays` of any shape by combining them with the `np.reshape()` function. The `np.reshape(ndarray, new_shape)` function converts the given `ndarray` into the specified **new_shape**. 

It is important to note that the **new_shape** should be compatible with the number of elements in the given `ndarray`. For example, you can convert a rank 1 `ndarray` with **6** elements into a **3 x 2** rank 2 `ndarray`, or a **2 x 3** rank 2 `ndarray`, since both of these rank 2 arrays will have a total of **6** elements. However, you can't reshape the rank 1 `ndarray` with **6** elements into a **3 x 3** rank 2 `ndarray`, since this rank 2 array will have **9** elements, which is greater than the number of elements in the original `ndarray`.

Let's see some examples:


In [24]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)

# We print x
print()
print('Original x = ', x)
print()

# We reshape x into a 4 x 5 ndarray 
x = np.reshape(x, (4,5))

# We print the reshaped x
print()
print('Reshaped x = \n', x)
print()

# We print information about the reshaped x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


One great feature about NumPy is that some functions can also be applied as methods. This allows us to apply different functions in sequence in just one line of code. 

`ndarray` methods are similar to `ndarray` attributes in that they are both applied using dot notation (**.**). 

Let's see how we can accomplish the same result as in the above example, but in just one line of code:


In [25]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


As we can see, we get the exact same result as before. Notice that when we use `reshape()` as a method, it's applied as `ndarray.reshape(new_shape)`. This converts the `ndarray` into the specified shape **new_shape**. 

As before, it is important to note that the **new_shape** should be compatible with the number of elements in the `ndarray`. In the example above, the function `np.arange(20)` creates an `ndarray` and serves as the `ndarray` to be reshaped by the `reshape()` method. Therefore, when using `reshape()` as a method, we don't need to pass the `ndarray` as an argument to the `reshape()` function; instead, we only need to pass the **new_shape** argument.

In the same manner, we can also combine `reshape()` with `np.linspace()` to create rank 2 arrays, as shown in the next example:


In [26]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


The last type of `ndarrays` we are going to create are **random ndarrays**. Random `ndarrays` are arrays that contain random numbers. Often in Machine Learning, you need to create random matrices, for example, when initializing the weights of a Neural Network. 

NumPy offers a variety of random functions to help us create random `ndarrays` of any shape.

Let's start by using the `np.random.random(shape)` function to create an `ndarray` of the given shape with random floats in the half-open interval \([0.0, 1.0)\).


In [27]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3,3))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.49933453 0.20267614 0.92647153]
 [0.71588819 0.40852991 0.58173437]
 [0.99557679 0.899992   0.02002869]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


NumPy also allows us to create `ndarrays` with random integers within a particular interval. The function `np.random.randint(start, stop, size=shape)` creates an `ndarray` of the given shape with random integers in the half-open interval \([ \text{start}, \text{stop} )\). 

Let's see an example:


In [28]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,size=(3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 7 12]
 [ 4  9]
 [ 4  6]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


In some cases, you may need to create `ndarrays` with random numbers that satisfy certain statistical properties. For example, you may want the random numbers in the `ndarray` to have an average of **0**. 

NumPy allows you to create random `ndarrays` with numbers drawn from various probability distributions. The function `np.random.normal(mean, standard deviation, size=shape)`, for example, creates an `ndarray` with the given shape that contains random numbers picked from a normal (Gaussian) distribution with the specified **mean** and **standard deviation**.

Let's create a **1,000 x 1,000** `ndarray` of random floating-point numbers drawn from a normal distribution with a mean (average) of **zero** and a standard deviation of **0.1**.


In [29]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[ 0.03045228  0.02413018 -0.02247063 ...  0.02119965 -0.18633778
  -0.00719837]
 [ 0.01267015  0.00844708 -0.02335088 ... -0.04915412  0.04993636
   0.08875049]
 [-0.11815497 -0.05192407 -0.00237234 ... -0.0826022  -0.0446146
   0.03368957]
 ...
 [-0.00352433 -0.09685225 -0.02132368 ... -0.10275485 -0.06271422
  -0.11825549]
 [ 0.11410412  0.02317583 -0.0475776  ...  0.02443173  0.06866853
   0.08743631]
 [-0.12896075 -0.00685277  0.06829483 ...  0.04151714 -0.20479053
  -0.04626453]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -0.0001518962354269824
The maximum value in X is: 0.4875314710554345
The minimum value in X is: -0.4658913945203293
X has 500386 negative numbers
X has 499614 positive numbers


As we can see, the average of the random numbers in the `ndarray` is close to **zero**. Both the maximum and minimum values in **X** are symmetric about zero (the average), and we have about the same amount of positive and negative numbers.


## Accessing, Deleting, and Inserting Elements Into ndarrays

Now that you know how to create a variety of `ndarrays`, we will see how NumPy allows us to effectively manipulate the data within them. 

**NumPy ndarrays are mutable**, meaning that the elements in `ndarrays` can be changed after the array has been created. Additionally, `ndarrays` can be **sliced**, which allows us to split them in many different ways. This feature enables us to retrieve any subset of the `ndarray` that we want. 

Often in Machine Learning, you will use slicing to separate data, such as when dividing a data set into **training**, **cross-validation**, and **testing** sets.

### Accessing Elements

We will start by looking at how the elements of an `ndarray` can be accessed or modified by indexing. Elements can be accessed using indices inside square brackets \([ ]\). 

NumPy allows you to use both **positive** and **negative indices** to access elements in the `ndarray`. Positive indices are used to access elements from the **beginning** of the array, while negative indices are used to access elements from the **end** of the array. 

Let's see how we can access elements in **rank 1 ndarrays**:


In [30]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('x = ', x)
print()

# Let's access some elements with positive indices
print('This is First Element in x:', x[0]) 
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])


x =  [1 2 3 4 5]

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


Notice that to access the **first element** in the `ndarray`, we have to use the index **0**, not **1**. Additionally, the same element can be accessed using both **positive** and **negative indices**. As mentioned earlier, positive indices are used to access elements from the **beginning** of the array, while negative indices are used to access elements from the **end** of the array.

### Changing Elements

Now let's see how we can change the elements in **rank 1 ndarrays**. We do this by accessing the element we want to change and then using the **`=`** sign to assign the new value:


In [31]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# We print the original x
print()
print('Original:\n x = ', x)
print()

# We change the fourth element in x from 4 to 20
x[3] = 20

# We print x after it was modified 
print('Modified:\n x = ', x)


Original:
 x =  [1 2 3 4 5]

Modified:
 x =  [ 1  2  3 20  5]


Similarly, we can also access and modify specific elements of **rank 2 ndarrays**. To access elements in **rank 2 ndarrays**, we need to provide **2 indices** in the form \([ \text{row}, \text{column} ]\). 

### Accessing Elements in Rank 2 ndarrays

Let's see some examples:


In [32]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print X
print()
print('X = \n', X)
print()

# Let's access some elements in X
print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])


X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


Remember that the index \([0, 0]\) refers to the element in the **first row**, **first column**.

### Modifying Elements in Rank 2 ndarrays

Elements in **rank 2 ndarrays** can be modified in the same way as with **rank 1 ndarrays**. Let's see an example:


In [33]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print the original x
print()
print('Original:\n X = \n', X)
print()

# We change the (0,0) element in X from 1 to 20
X[0,0] = 20

# We print X after it was modified 
print('Modified:\n X = \n', X)


Original:
 X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified:
 X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


Now, let's take a look at how we can **add** and **delete** elements from `ndarrays`. 

### Deleting Elements

We can delete elements using the **`np.delete(ndarray, elements, axis)`** function. This function deletes the given list of elements from the specified `ndarray` along the specified axis. 

- For **rank 1 ndarrays**, the **axis** keyword is not required.
- For **rank 2 ndarrays**, **`axis = 0`** is used to select **rows**, and **`axis = 1`** is used to select **columns**.

Let's see some examples:


In [34]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We delete the first and last element of x
x = np.delete(x, [0,4])

# We print x with the first and last element deleted
print()
print('Modified x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We delete the first row of y
w = np.delete(Y, 0, axis=0)

# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)


Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]


Now, let's see how we can **append values** to `ndarrays`. 

### Appending Values

We can append values to `ndarrays` using the **`np.append(ndarray, elements, axis)`** function. This function appends the given list of elements to the `ndarray` along the specified axis. 

Let's see some examples:


In [35]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

# We print x
print()
print('Original x = ', x)

# We append the integer 6 to x
x = np.append(x, 6)

# We print x
print()
print('x = ', x)

# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

# We print v
print()
print('v = \n', v)

# We print q
print()
print('q = \n', q)


Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]

Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


Notice that when appending **rows** or **columns** to **rank 2 ndarrays**, the rows or columns must have the **correct shape** to match the shape of the **rank 2 ndarray**.

### Inserting Values

Now let's see how we can **insert values** to `ndarrays`. We can insert values using the **`np.insert(ndarray, index, elements, axis)`** function. This function inserts the given list of elements into the `ndarray` right before the specified index along the specified axis.

Let's see some examples:


In [36]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])

# We print x with the inserted elements
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)


Original x =  [1 2 5 6 7]

x =  [1 2 3 4 5 6 7]

Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 5 2 3]
 [7 5 8 9]]


NumPy also allows us to **stack ndarrays** on top of each other or side by side. The stacking is done using:

- **`np.vstack()`** function for **vertical stacking**
- **`np.hstack()`** function for **horizontal stacking**

### Important Note
It is important to note that in order to stack `ndarrays`, the shape of the `ndarrays` must match.

Let's see some examples:


In [37]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]


## Slicing ndarrays

As we mentioned earlier, in addition to being able to access **individual elements** one at a time, NumPy provides a way to access **subsets** of `ndarrays`. This is known as **slicing**. Slicing is performed by combining indices with the colon `:` symbol inside the square brackets. In general, you will come across three types of slicing:

1. **`ndarray[start:end]`**
2. **`ndarray[start:]`**
3. **`ndarray[:end]`**

### Explanation
- The **first method** is used to select elements **between** the start and end indices.
- The **second method** is used to select all elements from the start index **till** the last index.
- The **third method** is used to select all elements from the first index **till** the end index.

**Important Note:** In methods one and three, the end index is **excluded**. Since `ndarrays` can be **multidimensional**, when doing slicing you usually have to specify a slice for **each dimension** of the array.

Now, let's see some examples of how to use the above methods to select different subsets of a **rank 2 ndarray**.


In [39]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)

# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print()
print('W = \n', W)

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

# We print Y
print()
print('Y = \n', Y)

# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

v =  [10 11 12 13 14]

q =  [ 2  7 12 17]

R = 
 [[ 2]
 [ 7]
 [12]
 [17]]




Notice that when we selected all the elements in the **3rd column**, the variable **q** returned a **rank 1 ndarray** instead of a **rank 2 ndarray**. However, slicing **X** in a slightly different way, as seen in variable **R**, allows us to obtain a **rank 2 ndarray**.

### Important Note
When we perform slices on `ndarrays` and save them into new variables, the data is **not copied** into the new variable. This is a common feature that can cause confusion for beginners. Let's delve into this concept a bit more.

For instance, when we make assignments such as:

```python
Z = X[1:4, 2:5]
```

The slice of the original array **X** is not copied into the variable **Z**. Instead, **X** and **Z** are now just two different names for the **same ndarray**. We say that slicing only creates a **view** of the original array. This means that if you make changes in **Z**, you will be effectively changing the elements in **X** as well.

### Example
Let's illustrate this with an example:


In [40]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]

# We print Z
print()
print('Z = \n', Z)
print()

# We change the last element in Z to 555
Z[2,2] = 555

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


X = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]





We can clearly see in the above example that if we make changes to **Z**, **X** changes as well.

### Creating a Copy of the ndarray
If we want to create a new `ndarray` that contains a **copy** of the values in the slice, we need to use the `np.copy()` function. The `np.copy(ndarray)` function creates a copy of the given `ndarray`. This function can also be used as a method, similar to how we used the `reshape` function.

### Example: Using np.copy()
Let's do the same example we did before but now with copies of the arrays. We'll use `copy` both as a function and as a method. 

- **Creating a rank 2 ndarray**
  
- **Slicing a part of X and creating a copy using np.copy()**

- **Slicing a part of X and creating a copy using the copy method**

- **Display the original array and the copied array**

- **Modifying the copied arrays**

- **Display the arrays after modification**



In [41]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

# We change the last element in Z to 555
Z[2,2] = 555

# We change the last element in W to 444
W[2,2] = 444

# We print X
print()
print('X = \n', X)

# We print Z
print()
print('Z = \n', Z)

# We print W
print()
print('W = \n', W)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]




We can clearly see that by using the **copy** command, we are creating new `ndarrays` that are completely independent of each other.

### Using One ndarray to Manipulate Another
It is often useful to use one `ndarray` to make slices, select, or change elements in another `ndarray`. Let's see some examples:


In [42]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We create a rank 1 ndarray that will serve as indices to select elements from X
indices = np.array([1,3])

# We print X
print()
print('X = \n', X)
print()

# We print indices
print('indices = ', indices)
print()

# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]

# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]

# We print Y
print()
print('Y = \n', Y)

# We print Z
print()
print('Z = \n', Z)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

indices =  [1 3]


Y = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]

Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]



NumPy also offers built-in functions to select specific elements within `ndarrays`. For example, the `np.diag(ndarray, k=N)` function extracts the elements along the diagonal defined by N. As default is **k=0**, which refers to the main diagonal. Values of **k > 0** are used to select elements in diagonals above the main diagonal, and values of **k < 0** are used to select elements in diagonals below the main diagonal. Let's see an example:

In [43]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('X = \n', X)
print()

# We print the elements in the main diagonal of X
print('z =', np.diag(X))
print()

# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=1))
print()

# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

z = [ 0  6 12 18 24]

y = [ 1  7 13 19]

w =  [ 5 11 17 23]


It is often useful to extract only the unique elements in an `ndarray`. We can find the unique elements in an `ndarray` by using the `np.unique()` function. The `np.unique(ndarray)` function returns the unique elements in the given `ndarray`, as in the example below:



In [44]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X
print()
print('X = \n', X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))


X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in X are: [1 2 3 5 8]




## Boolean Indexing, Set Operations, and Sorting

Up to now, we have seen how to make slices and select elements of an `ndarray` using indices. This is useful when we know the exact indices of the elements we want to select. However, there are many situations in which we don't know the indices of the elements we want to select. For example, suppose we have a 10,000 x 10,000 `ndarray` of random integers ranging from 1 to 15,000, and we only want to select those integers that are less than 20. Boolean indexing can help us in these cases, by allowing us to select elements using logical arguments instead of explicit indices. Let's see some examples:



In [45]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('Original X = \n', X)
print()

# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

# We print X
print()
print('X = \n', X)
print()


Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]





In addition to Boolean Indexing, NumPy also allows for set operations. This is useful when comparing `ndarrays`, for example, to find common elements between two `ndarrays`. Let's see some examples:



In [46]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]




We can also sort `ndarrays` in NumPy. We will learn how to use the `np.sort()` function to sort rank 1 and rank 2 `ndarrays` in different ways. Like with other functions we saw before, the sort function can also be used as a method. However, there is a big difference in how the data is stored in memory in this case. When `np.sort()` is used as a function, it sorts the `ndarrays` out of place, meaning that it doesn't change the original `ndarray` being sorted. However, when you use sort as a method, `ndarray.sort()` sorts the `ndarray` in place, meaning that the original array will be changed to the sorted one. Let's see some examples:



In [47]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a function.
print()
print('Sorted x (out of place):', np.sort(x))

# When we sort out of place the original array remains intact. To see this we print x again
print()
print('x after sorting:', x)


Original x =  [ 1  5  2  6 10  4  4  8  8  4]

Sorted x (out of place): [ 1  2  4  4  4  5  6  8  8 10]

x after sorting: [ 1  5  2  6 10  4  4  8  8  4]




Notice that `np.sort()` sorts the array, but if the `ndarray` being sorted has repeated values, `np.sort()` leaves those values in the sorted array. However, if desired, we can sort only the unique elements in `x` by combining the sort function with the unique function. Let's see how we can sort the unique elements of `x` above:



In [48]:
# We sort x but only keep the unique elements in x
print(np.sort(np.unique(x)))

[ 1  2  4  5  6  8 10]


Finally, let's see how we can sort ndarrays in place, by using sort as a method:

In [49]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a method.
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after sorting:', x)


Original x =  [ 2  6  9  4 10  1  4  2 10  6]

x after sorting: [ 1  2  2  4  4  6  6  9 10 10]




When sorting rank 2 ndarrays, we need to specify to the `np.sort()` function whether we are sorting by rows or columns. This is done by using the `axis` keyword. Let's see some examples:


In [50]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original X = 
 [[ 3  7  7  7  5]
 [10  9  1  8  4]
 [ 4  8  9  4  4]
 [ 6  8  4  9  2]
 [ 8  2  6  7 10]]


X with sorted columns :
 [[ 3  2  1  4  2]
 [ 4  7  4  7  4]
 [ 6  8  6  7  4]
 [ 8  8  7  8  5]
 [10  9  9  9 10]]

X with sorted rows :
 [[ 3  5  7  7  7]
 [ 1  4  8  9 10]
 [ 4  4  4  8  9]
 [ 2  4  6  8  9]
 [ 2  6  7  8 10]]




## Arithmetic Operations and Broadcasting

We have reached the last lesson in this Introduction to NumPy. In this last lesson, we will see how NumPy does arithmetic operations on ndarrays. NumPy allows element-wise operations on ndarrays as well as matrix operations. In this lesson, we will only be looking at element-wise operations on ndarrays. 

In order to do element-wise operations, NumPy sometimes uses something called **Broadcasting**. Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. For example, broadcasting is used implicitly when doing arithmetic operations between scalars and ndarrays.

Let's start by doing element-wise addition, subtraction, multiplication, and division between ndarrays. To do this, NumPy provides a functional approach, where we use functions such as `np.add()`, or by using arithmetic symbols, such as `+`, that resembles more how we write mathematical equations. Both forms will do the same operation; the only difference is that if you use the function approach, the functions usually have options that you can tweak using keywords. 

It is important to note that when performing element-wise operations, the shapes of the ndarrays being operated on must have the same shape or be broadcastable. We'll explain more about this later in this lesson. Let's start by performing element-wise arithmetic operations on rank 1 ndarrays:



In [51]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)
print()

# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))


x =  [1 2 3 4]

y =  [5.5 6.5 7.5 8.5]

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


We can also perform the same element-wise arithmetic operations on rank 2 ndarrays. Again, remember that in order to do these operations the shapes of the ndarrays being operated on, must have the same shape or be broadcastable.

In [52]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print()
print('X = \n', X)

# We print Y
print()
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))


X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


We can also apply mathematical functions, such as `sqrt(x)`, to all elements of an ndarray at once.

In [53]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4])

# We print x
print()
print('x = ', x)

# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2


x =  [1 2 3 4]

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]


Another great feature of NumPy is that it has a wide variety of statistical functions. Statistical functions provide us with statistical information about the elements in an ndarray. Let's see some examples:

In [54]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


Finally, let's see how NumPy can add single numbers to all the elements of an ndarray without the use of complicated loops.

In [55]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)


X = 
 [[1 2]
 [3 4]]

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]



In the examples above, NumPy is working behind the scenes to broadcast **3** along the ndarray so that they have the same shape. This allows us to add **3** to each element of **X** with just one line of code.

Subject to certain constraints, NumPy can do the same for two ndarrays of different shapes, as we can see below.



In [56]:
# We create a rank 1 ndarray
x = np.array([1,2,3])

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

# We print x
print()
print('x = ', x)
print()

# We print Y
print()
print('Y = \n', Y)
print()

# We print Z
print()
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)


x =  [1 2 3]


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Z = 
 [[1]
 [2]
 [3]]

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


As before, NumPy is able to add 1 x 3 and 3 x 1 ndarrays to 3 x 3 ndarrays by broadcasting the smaller ndarrays along the big ndarray so that they have compatible shapes. In general, NumPy can do this provided that the smaller ndarray, such as the 1 x 3 ndarray in our example, can be expanded to the shape of the larger ndarray in such a way that the resulting broadcast is unambiguous.

# 🚀 NumPy Fundamentals: Quick Recap

## 📊 Core Concepts

1. **ndarray Basics**
   - Creation: `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`
   - Indexing & Slicing: `arr[0]`, `arr[1:5]`, `arr[::2]`
   - Views vs Copies: `arr.view()` vs `arr.copy()`

2. **Advanced Selection**
   - Boolean indexing: `arr[arr > 5]`
   - Set ops: `np.intersect1d()`, `np.setdiff1d()`, `np.union1d()`
   - Sorting: `np.sort()`, `arr.sort()`

3. **Arithmetic & Broadcasting**
   - Element-wise ops: `+`, `-`, `*`, `/`
   - Broadcasting: Operating on arrays with different shapes
   - Stats: `np.mean()`, `np.sum()`, `np.std()`, `np.median()`

4. **Practical Examples**
   - Unique elements: `np.unique()`
   - Diagonal extraction: `np.diag()`
   - Advanced indexing: `arr[[1,3,5]]`
   - Math functions: `np.sin()`, `np.exp()`

## 🎓 Key Takeaways

- NumPy provides efficient array operations
- Broadcasting enables flexible computations
- Rich set of functions for data manipulation and analysis

## 💡 Pro Tips

1. Use vectorized operations for speed
2. Leverage broadcasting to write concise code
3. Explore NumPy's extensive documentation for more advanced features

Keep practicing and experimenting with NumPy to master these fundamentals!